# File: .readthedocs.yaml
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#using-a-configuration-file

version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - requirements: .docs/sphinx_requirements.txt

sphinx:
   configuration: .docs/conf.py
